package com.agentjar.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.application.WriteAction
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import java.io.IOException

/**
 * Action to generate a Dockerfile for Spring Boot applications.
 */
class GenerateDockerfileAction : AnAction() {
    
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val baseDir = project.baseDir
        
        if (baseDir == null) {
            Messages.showErrorDialog(project, "Cannot find project directory", "Docker Error")
            return
        }
        
        // Check if Dockerfile already exists
        val existingDockerfile = baseDir.findChild("Dockerfile")
        if (existingDockerfile != null) {
            val response = Messages.showYesNoDialog(
                project,
                "Dockerfile already exists. Overwrite it?",
                "Dockerfile Exists",
                Messages.getQuestionIcon()
            )
            if (response != Messages.YES) return
        }
        
        // Detect build tool
        val buildTool = detectBuildTool(baseDir)
        
        try {
            WriteAction.run<IOException> {
                createDockerfile(baseDir, buildTool)
                createDockerignore(baseDir)
            }
            
            Messages.showInfoMessage(
                project,
                "Dockerfile and .dockerignore created successfully!\n\n" +
                        "Build tool detected: $buildTool\n\n" +
                        "To build: docker build -t ${project.name} .\n" +
                        "To run: docker run -p 8080:8080 ${project.name}",
                "Docker Files Created"
            )
        } catch (ex: IOException) {
            Messages.showErrorDialog(
                project,
                "Failed to create Docker files: ${ex.message}",
                "Docker Error"
            )
        }
    }
    
    override fun update(e: AnActionEvent) {
        e.presentation.isEnabled = e.project != null
    }
    
    private fun detectBuildTool(baseDir: VirtualFile): String {
        return when {
            baseDir.findChild("pom.xml") != null -> "Maven"
            baseDir.findChild("build.gradle") != null || baseDir.findChild("build.gradle.kts") != null -> "Gradle"
            else -> "Maven"  // Default to Maven
        }
    }
    
    private fun createDockerfile(baseDir: VirtualFile, buildTool: String) {
        val dockerfileContent = when (buildTool) {
            "Gradle" -> gradleDockerfile()
            else -> mavenDockerfile()
        }
        
        val dockerfile = baseDir.findChild("Dockerfile") ?: baseDir.createChildData(this, "Dockerfile")
        VfsUtil.saveText(dockerfile, dockerfileContent)
    }
    
    private fun createDockerignore(baseDir: VirtualFile) {
        val dockerignore = baseDir.findChild(".dockerignore") ?: baseDir.createChildData(this, ".dockerignore")
        VfsUtil.saveText(dockerignore, dockerignoreContent())
    }
    
    private fun mavenDockerfile(): String = """
        # Multi-stage build for Spring Boot with Maven
        # Generated by AgentJar plugin
        
        # Stage 1: Build
        FROM eclipse-temurin:17-jdk-alpine AS build
        WORKDIR /app
        
        # Copy Maven wrapper and pom.xml
        COPY mvnw .
        COPY .mvn .mvn
        COPY pom.xml .
        
        # Download dependencies (cached layer)
        RUN ./mvnw dependency:go-offline -B
        
        # Copy source code
        COPY src src
        
        # Build application
        RUN ./mvnw package -DskipTests
        
        # Stage 2: Runtime
        FROM eclipse-temurin:17-jre-alpine
        WORKDIR /app
        
        # Copy JAR from build stage
        COPY --from=build /app/target/*.jar app.jar
        
        # Create non-root user
        RUN addgroup -g 1001 -S appuser && \
            adduser -u 1001 -S appuser -G appuser
        USER appuser
        
        # Expose port
        EXPOSE 8080
        
        # Health check
        HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
          CMD wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1
        
        # Run application
        ENTRYPOINT ["java", "-jar", "app.jar"]
    """.trimIndent()
    
    private fun gradleDockerfile(): String = """
        # Multi-stage build for Spring Boot with Gradle
        # Generated by AgentJar plugin
        
        # Stage 1: Build
        FROM eclipse-temurin:17-jdk-alpine AS build
        WORKDIR /app
        
        # Copy Gradle wrapper and configuration
        COPY gradlew .
        COPY gradle gradle
        COPY build.gradle.kts .
        COPY settings.gradle.kts .
        
        # Download dependencies (cached layer)
        RUN ./gradlew dependencies --no-daemon
        
        # Copy source code
        COPY src src
        
        # Build application
        RUN ./gradlew bootJar --no-daemon
        
        # Stage 2: Runtime
        FROM eclipse-temurin:17-jre-alpine
        WORKDIR /app
        
        # Copy JAR from build stage
        COPY --from=build /app/build/libs/*.jar app.jar
        
        # Create non-root user
        RUN addgroup -g 1001 -S appuser && \
            adduser -u 1001 -S appuser -G appuser
        USER appuser
        
        # Expose port
        EXPOSE 8080
        
        # Health check
        HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
          CMD wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1
        
        # Run application
        ENTRYPOINT ["java", "-jar", "app.jar"]
    """.trimIndent()
    
    private fun dockerignoreContent(): String = """
        # Build artifacts
        target/
        build/
        bin/
        out/
        
        # IDE files
        .idea/
        .vscode/
        *.iml
        *.ipr
        *.iws
        
        # Git
        .git/
        .gitignore
        
        # OS files
        .DS_Store
        Thumbs.db
        
        # Logs
        *.log
        logs/
        
        # Testing
        .pytest_cache/
        htmlcov/
        
        # Documentation
        README.md
        docs/
        
        # Docker
        Dockerfile
        .dockerignore
    """.trimIndent()
}
