package com.agentjar.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.application.WriteAction
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import java.io.IOException

/**
 * Action to scaffold a minimal Spring Boot project structure.
 */
class ScaffoldSpringBootAction : AnAction() {
    
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val baseDir = project.baseDir
        
        if (baseDir == null) {
            Messages.showErrorDialog(project, "Cannot find project directory", "Scaffold Error")
            return
        }
        
        // Check if Spring Boot project already exists
        if (isSpringBootProject(baseDir)) {
            val response = Messages.showYesNoDialog(
                project,
                "This appears to be a Spring Boot project already. Continue anyway?",
                "Spring Boot Detected",
                Messages.getQuestionIcon()
            )
            if (response != Messages.YES) return
        }
        
        try {
            WriteAction.run<IOException> {
                createSpringBootStructure(baseDir, project)
            }
            
            Messages.showInfoMessage(
                project,
                "Spring Boot project structure created successfully!\n\n" +
                        "Created:\n" +
                        "- src/main/java/com/agentjar/demo/DemoApplication.java\n" +
                        "- src/main/resources/application.properties\n" +
                        "- README.md",
                "Scaffold Complete"
            )
        } catch (ex: IOException) {
            Messages.showErrorDialog(
                project,
                "Failed to create project structure: ${ex.message}",
                "Scaffold Error"
            )
        }
    }
    
    override fun update(e: AnActionEvent) {
        e.presentation.isEnabled = e.project != null
    }
    
    private fun isSpringBootProject(baseDir: VirtualFile): Boolean {
        // Check for common Spring Boot indicators
        return baseDir.findChild("pom.xml") != null ||
                baseDir.findChild("build.gradle") != null ||
                baseDir.findChild("build.gradle.kts") != null
    }
    
    private fun createSpringBootStructure(baseDir: VirtualFile, project: Project) {
        // Create directory structure
        val srcMainJava = VfsUtil.createDirectories("${baseDir.path}/src/main/java/com/agentjar/demo")
        val srcMainResources = VfsUtil.createDirectories("${baseDir.path}/src/main/resources")
        
        // Create DemoApplication.java
        val appFile = srcMainJava.createChildData(this, "DemoApplication.java")
        VfsUtil.saveText(appFile, demoApplicationSource())
        
        // Create application.properties
        val propsFile = srcMainResources.createChildData(this, "application.properties")
        VfsUtil.saveText(propsFile, applicationPropertiesSource())
        
        // Create README.md
        val readmeFile = baseDir.createChildData(this, "README.md")
        VfsUtil.saveText(readmeFile, readmeSource())
    }
    
    private fun demoApplicationSource(): String = """
        package com.agentjar.demo;
        
        import org.springframework.boot.SpringApplication;
        import org.springframework.boot.autoconfigure.SpringBootApplication;
        
        /**
         * Spring Boot application entry point.
         * Generated by AgentJar plugin.
         */
        @SpringBootApplication
        public class DemoApplication {
            public static void main(String[] args) {
                SpringApplication.run(DemoApplication.class, args);
            }
        }
    """.trimIndent()
    
    private fun applicationPropertiesSource(): String = """
        # Spring Boot Application Configuration
        # Generated by AgentJar plugin
        
        spring.application.name=agentjar-demo
        server.port=8080
        
        # Logging
        logging.level.root=INFO
        logging.level.com.agentjar=DEBUG
    """.trimIndent()
    
    private fun readmeSource(): String = """
        # AgentJar Spring Boot Demo
        
        This is a minimal Spring Boot application scaffolded by the AgentJar plugin.
        
        ## Getting Started
        
        ### Prerequisites
        - Java 17 or higher
        - Maven or Gradle (add your build file)
        
        ### Running the Application
        
        ```bash
        # With Maven
        mvn spring-boot:run
        
        # With Gradle
        ./gradlew bootRun
        ```
        
        ### Next Steps
        
        1. Add your build configuration (pom.xml or build.gradle)
        2. Create REST controllers in `src/main/java/com/agentjar/demo`
        3. Add service layer components
        4. Configure database connections in application.properties
        
        ---
        Generated by [AgentJar](https://agentjar.dev) - Agentic IDE for Spring Boot
    """.trimIndent()
}
